awesome-academy/HN_OE49_PHP_Shoe_Store

app/Models/Brand.php, app/Models/Comment.php, app/Models/Image.php, app/Models/Order.php, app/Models/OrderStatus.php, app/Models/Product.php, app/Models/Role.php, app/Models/User.php, database/migrations/2022_02_24_101547_create_roles_table.php, database/migrations/2022_02_24_101634_create_users_table.php, database/migrations/2022_02_24_101706_create_order_statuses_table.php, database/migrations/2022_02_24_101733_create_orders_table.php, database/migrations/2022_02_24_101759_create_brands_table.php, database/migrations/2022_02_24_101824_create_products_table.php, database/migrations/2022_02_24_101844_create_images_table.php, database/migrations/2022_02_24_101906_create_comments_table.php, database/migrations/2022_02_24_101932_create_order_products_table.php, tests/Feature/ExampleTest.php, tests/Unit/ExampleTest.php
- [#46195](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/46195)
- Create Model & Migration
- N/A.
- N/A.
=> Tao model & migration

app/Http/Controllers/ProductController.php, database/migrations/2022_02_28_092525_update_images_table.php, public/mix-manifest.json, resources/css/styleP.css, resources/js/delete.js, resources/lang/en.json, resources/lang/vi.json, resources/views/layouts/appAdmin.blade.php, resources/views/products/create.blade.php, resources/views/products/edit.blade.php, resources/views/products/index.blade.php, routes/web.php, webpack.mix.js
- [#46205](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/46205)
- Create view admin CRUD product
- N/A.
- N/A.
=> create view admin CRUD product

app/Http/Controllers/BrandController.php, app/Http/Requests/Brands/StoreRequest.php, app/Http/Requests/Brands/UpdateRequest.php, app/Models/Brand.php, resources/lang/vi.json, routes/web.php
- [#46203](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/46203)
Xử lý logic CRUD cho brand
- N/A.
- N/A.
=> BE CRUD brand

app/Http/Controllers/ProductController.php, app/Http/Requests/Products/StoreRequest.php, app/Models/Image.php, app/Models/Product.php, resources/views/admins/products/create.blade.php, resources/views/admins/products/edit.blade.php, resources/views/admins/products/index.blade.php, resources/views/admins/products/show.blade.php
- [#46206](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/46206)
- BE create & show product
- N/A.
- N/A.
=> BE create & show product

resources/css/styleP.css, resources/lang/en.json, resources/lang/vi.json, resources/views/layouts/app.blade.php, resources/views/users/showByBrand.blade.php
- [#46219](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/46219)
- Create form show products by brand
- Show products after searching by name
- Pagination of display and search
- N/A.
- N/A.
=> create form show products by brand and searchproduct by name

app/Http/Controllers/UserProductController.php, app/Providers/AppServiceProvider.php, config/paginate.php, routes/web.php
- [#46221](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/46221)
- Xử lý logic hiển thị sản phẩm theo thương hiệu
- Tìm kiếm sản phẩm theo tên và phân trang theo tìm kiếm
- N/A.
- N/A.
=> BE show products by brand and search product by name

.gitignore, app/Http/Controllers/ProfileController.php, app/Http/Requests/Profile/UpdateRequest.php, resources/css/styleP.css, resources/js/script.js, resources/lang/en.json, resources/lang/vi.json, resources/views/layouts/app.blade.php, resources/views/users/profile/edit.blade.php, resources/views/users/profile/show.blade.php, routes/web.php
- [#46239](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/46239)
- BE edit profile user
- N/A.
- N/A.
=> BE edit profile user

resources/css/styleP.css, resources/lang/en.json, resources/lang/vi.json, resources/views/layouts/app.blade.php, resources/views/users/cart.blade.php, resources/views/users/profile/edit.blade.php, resources/views/users/profile/show.blade.php, resources/views/users/shop.blade.php, resources/views/users/show.blade.php, resources/views/users/showByBrand.blade.php
- [#46229](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/46229)
create form cart
- N/A.
- N/A.
=> create form cart

app/Http/Controllers/UserProductController.php, app/Models/Product.php, config/database.php, config/rating.php, public/mix-manifest.json, resources/lang/en.json, resources/lang/vi.json, resources/views/users/shop.blade.php, resources/views/users/show.blade.php, resources/views/users/showByBrand.blade.php
- [#46218](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/46218)
- Display products by rating
- N/A.
- N/A.
=> Display products by rating

.bowerrc, .gitignore, bower.json, package-lock.json, package.json, resources/css/main.css, resources/js/script.js, resources/views/layouts/app.blade.php, resources/views/users/show.blade.php
- [#46235](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/46235)
Tạo giao diện comment
- N/A.
- N/A.
=> create form comment

app/Http/Controllers/CommentController.php, app/Http/Controllers/UserProductController.php, app/Http/Requests/Comments/CommentRequest.php, app/Models/Comment.php, config/orderstatus.php, resources/lang/en.json, resources/lang/vi.json, resources/views/users/show.blade.php, routes/web.php
- [#46236](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/46236)
Xử lý chức năng đánh giá và thêm comment chỉ khi người dùng đã mua hàng
- N/A.
- N/A.
=> Logic add comment

resources/css/main.css, resources/js/script.js, resources/lang/en.json, resources/lang/vi.json, resources/views/admins/orders/detail.blade.php, resources/views/admins/orders/edit.blade.php, resources/views/admins/orders/index.blade.php, resources/views/admins/products/edit.blade.php, resources/views/admins/products/index.blade.php, resources/views/layouts/app.blade.php, resources/views/layouts/appAdmin.blade.php
- [#46209](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/46209)
Create form show and edit order status
- N/A.
- N/A.
=> Order management

app/Http/Controllers/AdminOrderController.php, app/Http/Controllers/ProductController.php, app/Http/Requests/Orders/UpdateRequest.php, app/Models/Order.php, app/Models/Product.php, routes/web.php
- [#46210](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/46210)
Xử lý logic update trạng thái đơn order
Update lại số lượng sp nếu order bị hủy
- N/A.
- N/A.
=> Logic update order status

app/Http/Controllers/OrderController.php, app/Http/Controllers/ProductController.php, app/Http/Requests/Products/StoreRequest.php, app/Http/Requests/Products/UpdateRequest.php, app/Models/Order.php, resources/lang/en.json, resources/lang/vi.json, resources/views/admins/products/edit.blade.php, resources/views/layouts/app.blade.php, resources/views/users/history/index.blade.php, resources/views/users/history/show.blade.php, routes/web.php
- [#46233](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/46233)
- Order History
- Fix edit product
- N/A.
- N/A.
=> Order history

app/Http/Controllers/AdminOrderController.php, app/Http/Controllers/Auth/LoginController.php, app/Http/Controllers/BrandController.php, app/Http/Controllers/CartController.php, app/Http/Controllers/ProductController.php, app/Http/Controllers/ProfileController.php, app/Http/Controllers/UserController.php, config/paginate.php, resources/lang/en.json, resources/lang/vi.json, resources/views/admins/brands/index.blade.php, resources/views/admins/orders/index.blade.php, resources/views/admins/products/index.blade.php, resources/views/admins/users/index.blade.php, resources/views/auth/login.blade.php, resources/views/users/cart.blade.php, resources/views/users/profile/show.blade.php
- [#46530](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/46530)
- Modify logic login user
- Add paginate form
- N/A.
- N/A.
=> Modify login user and add paginate form

app/Http/Controllers/CommentController.php, app/Http/Controllers/UserProductController.php, app/Http/Requests/Comments/StoreRequest.php, app/Http/Requests/Comments/UpdateRequest.php, app/Http/Requests/Products/StoreRequest.php, app/Http/Requests/Products/UpdateRequest.php, resources/css/main.css, resources/js/script.js, resources/lang/en.json, resources/lang/vi.json, resources/views/admins/products/edit.blade.php, resources/views/layouts/app.blade.php, resources/views/layouts/appAdmin.blade.php, resources/views/users/all.blade.php, resources/views/users/history/index.blade.php, resources/views/users/show.blade.php, routes/web.php
- [#46890](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/46890)
Modify logic add comment
Add logic update, delete comment
- N/A.
- N/A.
=> Modify logic comment

app/Http/Controllers/AdminOrderController.php, app/Http/Controllers/CartController.php, app/Http/Controllers/HomeController.php, app/Http/Controllers/OrderController.php, app/Http/Controllers/ProductController.php, resources/js/script.js, resources/lang/en.json, resources/lang/vi.json, resources/views/admins/orders/detail.blade.php, resources/views/admins/orders/index.blade.php, resources/views/admins/products/index.blade.php, resources/views/home.blade.php, resources/views/layouts/app.blade.php, resources/views/users/history/index.blade.php, resources/views/users/history/show.blade.php, resources/views/users/show.blade.php, routes/web.php
- [#47029](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/47029)
- Sửa lại layout một số form
- Thêm chức năng tìm kiếm cho user và admin
- Thêm chức năng hủy đơn hàng cho user
- N/A.
- N/A.
=> Search for user and admin

app/Http/Controllers/OrderController.php, app/Http/Controllers/UserProductController.php, resources/js/script.js, resources/lang/en.json, resources/lang/vi.json, resources/views/users/history/show.blade.php, routes/web.php
- [#47070](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/47070)
fix bug update product quantity after change order status
- N/A.
- N/A.
=> fix bug update product quantity after change order status

.gitignore, app/Models/Image.php, tests/ModelTestCase.php, tests/Unit/Models/BrandTest.php, tests/Unit/Models/CommentTest.php, tests/Unit/Models/ImageTest.php, tests/Unit/Models/OrderProductTest.php, tests/Unit/Models/OrderTest.php
- [#](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues)
Viết unit test cho 5 model: brand, comment, image, order product, order
- N/A.
- N/A.
=> create unittest for brand, comment, image, order_product, order

app/Models/Product.php, database/factories/BrandFactory.php, database/factories/CommentFactory.php, database/factories/ProductFactory.php, database/factories/UserFactory.php, tests/Unit/Models/OrderStatusTest.php, tests/Unit/Models/ProductTest.php, tests/Unit/Models/RoleTest.php, tests/Unit/Models/UserTest.php
- [#47407](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/47407)
create model user, role, product, orderstatus
- N/A.
- N/A.
=> create model user, role, product, orderstatus

app/Http/Controllers/AdminOrderController.php, app/Providers/AppServiceProvider.php, app/Repositories/BaseRepository.php, app/Repositories/Order/OrderRepository.php, app/Repositories/Order/OrderRepositoryInterface.php, app/Repositories/OrderStatus/OrderStatusRepository.php, app/Repositories/OrderStatus/OrderStatusRepositoryInterface.php, app/Repositories/Product/ProductRepository.php, app/Repositories/Product/ProductRepositoryInterface.php, app/Repositories/RepositoryInterface.php, database/factories/OrderFactory.php, tests/Unit/Http/Controller/AdminOrderControllerTest.php
- [#47455](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/47455)
- Viết unit test cho AdminOrderController
- N/A.
https://user-images.githubusercontent.com/61032909/159636657-b5f81b03-3df4-45c5-a283-b669652fce01.png
=> unit test AdminOrderController

composer.json, composer.lock, tests/Browser/ExampleTest.php, tests/Browser/Pages/HomePage.php, tests/Browser/Pages/Page.php, tests/Browser/console/.gitignore, tests/Browser/screenshots/.gitignore, tests/Browser/source/.gitignore, tests/DuskTestCase.php
- [#47634](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/47634)
Laravel dusk
- N/A.
- N/A.
=> Laravel dusk

app/Http/Controllers/ProfileController.php, app/Providers/AppServiceProvider.php, app/Repositories/Brand/BrandRepository.php, app/Repositories/Brand/BrandRepositoryInterface.php, app/Repositories/User/UserRepository.php, app/Repositories/User/UserRepositoryInterface.php, tests/Unit/Http/Controller/ProfileControllerTest.php
- [#47456](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/47456)
- unit test ProfileController
- N/A.
- N/A.
=> unit test controller ProfileController

resources/views/admins/products/index.blade.php, tests/Browser/admins/products/IndexTest.php
- [#47635](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/47635)
unit test view index product
- N/A.
- N/A.
=> unit test view index product

app/Http/Controllers/BrandController.php, app/Http/Controllers/CartController.php, app/Http/Controllers/CommentController.php, app/Http/Controllers/HomeController.php, app/Providers/AppServiceProvider.php, app/Repositories/Brand/BrandRepository.php, app/Repositories/Brand/BrandRepositoryInterface.php, app/Repositories/Comment/CommentRepository.php, app/Repositories/Comment/CommentRepositoryInterface.php, app/Repositories/OrderProduct/OrderDetailRepository.php, app/Repositories/OrderProduct/OrderProductRepositoryInterface.php, app/Repositories/Product/ProductRepository.php, app/Repositories/Product/ProductRepositoryInterface.php, app/Repositories/User/UserRepository.php, resources/views/users/cart.blade.php
- [#47791](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/47791)
Triển khai Repository cho brand, cart, comment, home controller
- N/A.
- N/A.
=> repository brand, cart, comment, home controller

app/Http/Controllers/OrderController.php, app/Http/Controllers/ProductController.php, app/Http/Controllers/UserController.php, app/Http/Controllers/UserProductController.php, app/Providers/AppServiceProvider.php, app/Repositories/Comment/CommentRepositoryInterface.php, app/Repositories/Image/ImageRepository.php, app/Repositories/Image/ImageRepositoryInterface.php, app/Repositories/Order/OrderRepository.php, app/Repositories/Order/OrderRepositoryInterface.php, app/Repositories/Product/ProductRepository.php, app/Repositories/Product/ProductRepositoryInterface.php, app/Repositories/User/UserRepository.php, app/Repositories/User/UserRepositoryInterface.php
- [#47792(https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/47792)
Apply repo for order, product, user, userProduct controller
- N/A.
- N/A.
=> Apply repo for order, product, user, userProduct controller

app/Http/Controllers/AdminController.php, app/Repositories/Product/ProductRepository.php, app/Repositories/Product/ProductRepositoryInterface.php, package-lock.json, package.json, public/mix-manifest.json, resources/js/script.js, resources/lang/en.json, resources/lang/vi.json, resources/views/admins/dashboard.blade.php, resources/views/layouts/appAdmin.blade.php, webpack.mix.js
- [#48037](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/48037)
Chart of the number of products sold by each brand
- N/A.
=> Chart of the number of products sold by each brand

app/Events/NotificationEvent.php, app/Http/Controllers/NotificationController.php, app/Http/Controllers/OrderController.php, app/Notifications/OrderNotification.php, composer.json, composer.lock, config/app.php, config/broadcasting.php, database/migrations/2022_04_08_030721_create_notifications_table.php, package-lock.json, package.json, resources/css/main.css, resources/js/bootstrap.js, resources/js/script.js, resources/lang/en.json, resources/lang/vi.json, resources/views/admins/dashboard.blade.php, resources/views/layouts/app.blade.php, routes/web.php
- [#48096](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/48096)
send notification when user successfully place an order
- N/A.
- N/A.
=> send notification when user successfully place an order

app/Http/Controllers/AdminController.php, app/Repositories/Product/ProductRepository.php, app/Repositories/Product/ProductRepositoryInterface.php, resources/js/script.js, resources/lang/en.json, resources/lang/vi.json, resources/views/admins/dashboard.blade.php
- [#48153](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/48153)
Fix bug statistic quantity sold of each brand
- N/A.
=> Fix bug statistic quantity sold of each brand

app/Http/Controllers/AdminOrderController.php, app/Http/Controllers/OrderController.php, app/Mail/OrderShipped.php, app/Notifications/OrderNotification.php, app/Repositories/User/UserRepository.php, app/Repositories/User/UserRepositoryInterface.php, tests/Unit/Mail/OrderShippedTest.php, tests/Unit/Notification/OrderNotificationTest.php
- [#48099](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/48099)
Viết unit test gửi mail khi user đặt hàng thành công và gửi thông báo
- N/A.
=> unit test mail and notification

app/Http/Controllers/Api/AuthController.php, app/Http/Kernel.php, app/Repositories/User/UserRepository.php, app/Repositories/User/UserRepositoryInterface.php, composer.json, composer.lock, routes/api.php
- [#48803](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/48803)
Write API for login, logout
- N/A.
=> login logout api

app/Http/Controllers/Api/RegisterController.php, app/Http/Requests/RegisterRequest.php, app/Repositories/User/UserRepository.php, app/Repositories/User/UserRepositoryInterface.php, routes/api.php
- [#48805](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/48805)
Register API
- N/A.
=> Register API

app/Http/Controllers/Api/BrandController.php, app/Http/Kernel.php, app/Http/Middleware/CheckAdminLoginApi.php, app/Http/Resources/BrandResource.php, resources/lang/en.json, resources/lang/vi.json, routes/api.php
- [#48891](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/48891)
manage brand API
- N/A.
=> manage brand API

app/Http/Controllers/Api/UserController.php, app/Http/Resources/UserResource.php, routes/api.php
- [#48928](https://edu-redmine.sun-asterisk.vn/projects/hn_oe49-shoe-store/issues/48928)
- API for user management
- N/A.
=> api manage user
